### ISSUE TITLE
Patterning system!

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/proto-rising#23]
I have only the faintest sense of how the patterning system is going to work across module types. We may want to loop back and re-review this with Diana and write it up and start working on something, as it seems quite complex?

**Comment by adrian-the-git** [comment]
I have a pretty good sense after some conversations with Diana.

**Comment by phillipadsmith** [comment]
> I have a pretty good sense after some conversations with Diana.

That's great. 

Related note: have you had a chance to review the other issues to see if they accurate encompass the work ahead?

**Comment by phillipadsmith** [comment]
This issue was moved to BeautifulTrouble/beautiful-rising#25

**Comment by phillipadsmith** [comment]
This issue was moved to BeautifulTrouble/beautiful-rising#26
